<!DOCTYPE html>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>

<html>
	<head>
		<title>Login!</title>
		<link href="https://fonts.googleapis.com/css2?family=VT323&display=swap" rel="stylesheet">
		<link rel="stylesheet" href="${pageContext.request.contextPath}/css/styles.css" />
		
		<style type="text/css">
		.error {
			color: red;
			font-family: 'VT323', monospace;
			font-size: 30px;
		}
		.text{
			color: white;
			font-family: 'VT323', monospace;
			font-size: 30px;
			font-size: 2vw;
		}

		.button {
			background-color: black;
			border: 2px solid white;
			color: white;
			text-align: center;
			text-decoration: none;
			display: inline-block;
			font-size: 2vw;
			font-family: 'VT323', monospace;
		}

		</style>

		<link rel="stylesheet" href="${pageContext.request.contextPath}/css/styles.css" />
		
	</head>

	<body>

                   
          <div class="test-title">
        <pre>
                                      `-----------------------.    `----------.      -----------   .-----------------------`                                     `----------------..``                   `.:+++++/-`                    `.:+++++/-`          `-------.            .--------`                                       
			              +MMMMNmdhdMMMMMmhhdmNMMMN`   -syNMMMMMdyo     `symMMMMMmys`  /syNMMMMMdysssssyhmNMMMMy                                     :sydMMMMMmyssyydmNNmds:`             `:ymMNdyoshNMmy:`              `:ymMNmyoshNMNh/`       :shNMMMMd            dMMMMMNys.                                       
			           mMMN+.    mMMMM-    .yMMM/      /MMMMd           `MMMMM`        /MMMMd          -oNMMM:                                        NMMMM-      `-sNMMMm/           :dMMMy-     .oNMMd:            -hMMMh-     `+NMMd:         oMMMMM-          :MMMMMM:                                          
			          /MMN-      mMMMM.      sMMd      :MMMMh           `MMMMM         :MMMMh            `yMMm`                                       mMMMM.         -NMMMM/         oMMMM+         -NMMM+          +NMMMo         .mMMMo        +MMMMMy          hMMMMMM-                                          
			          dMN:       mMMMM.       yMM-     :MMMMh           `MMMMM         :MMMMh              +NN+                                       mMMMM.          +MMMMN`       sMMMMo           /MMMMo        oMMMMs           :MMMMs       +MMMMMM`        -MMMMMMM-                                          
			         `os/        mMMMM.       `ss-     :MMMMh           `MMMMM         :MMMMh               .-`                                       mMMMM.          .MMMMM.      /MMMMd             dMMMM/      :MMMMm`            yMMMM+      +MMMMMMo        yMMMMMMM-                                          
			                     mMMMM.                :MMMMh           `MMMMM         :MMMMh         .--                                             mMMMM.          .MMMMM`     `NMMMM+             /MMMMm`     mMMMMo             :MMMMN`     +MMNMMMm       .MMmmMMMM-                                          
			                     mMMMM.                :MMMMh           `MMMMM         :MMMMh         sMM`                                            mMMMM.          oMMMMh      +MMMMM`             `MMMMM+    /MMMMM-              NMMMMo     +MM+MMMM/      sMM/mMMMM-                                          
			                     mMMMM.                :MMMMh           `MMMMM         :MMMMh         dMM`                                            mMMMM.         /NMMMd`      hMMMMm               mMMMMd    yMMMMN               hMMMMm     +MM-mMMMd     `NMN mMMMM-                                          
			                     mMMMM.                :MMMMh           `MMMMM         :MMMMd`````.-/hMMM`                                            mMMMM.      ./hMMMm+`       NMMMMd               hMMMMN    mMMMMm               yMMMMM`    +MM-+MMMM-    oMMo mMMMM-                                          
			                     mMMMM.                :MMMMNddddddddddddMMMMM         :MMMMNhhhhhhdNMMMM`                                            mMMMMdhhhhdNMMNhs:         `MMMMMh               yMMMMM`   NMMMMd               sMMMMM.    +MM-`NMMMy   `NMN` mMMMM-                                          
			                     mMMMM.                :MMMMh           `MMMMM         :MMMMh       `oMMM`                                            mMMMM-```oMMMM/            `MMMMMh               yMMMMM`   NMMMMd               sMMMMM.    +MM- sMMMM.  +MMs  mMMMM-                                          
			                     mMMMM.                :MMMMh           `MMMMM         :MMMMh         hMM`                                            mMMMM.    dMMMN.            NMMMMh               hMMMMM    mMMMMm               sMMMMM`    +MM- .MMMMo  mMM.  mMMMM-                                          
			                     mMMMM.                :MMMMh           `MMMMM         :MMMMh         oNN`                                            mMMMM.    .NMMMd`           dMMMMm               dMMMMm    yMMMMN               hMMMMN     +MM-  hMMMN /MMy   mMMMM-                                          
			                     mMMMM.                :MMMMh           `MMMMM         :MMMMh                                                         mMMMM.     /MMMMs           +MMMMM`              NMMMMs    /MMMMM.              mMMMMy     +MM-  /MMMM/dMM-   mMMMM-                                          
			                     mMMMM.                :MMMMh           `MMMMM         :MMMMh                                                         mMMMM.      yMMMM/          `NMMMM:             .MMMMM.    `mMMMM/             .MMMMM-     +MM-   mMMMMMMd    mMMMM-                                          
			                     mMMMM.                :MMMMh           `MMMMM         :MMMMh               `ys-                                      mMMMM.      `mMMMN.          +MMMMh             oMMMMs      /MMMMd             +MMMMy      +MM-   oMMMMMM/    mMMMM-                                          
			                     mMMMM.                :MMMMh           `MMMMM         :MMMMh              `hMN`                                      mMMMM.       :MMMMd`          sMMMM:           `NMMMh`       oMMMM/           `mMMMd`      +MM-   `MMMMMm     mMMMM-                                          
			                     mMMMM.                :MMMMh           `MMMMM         :MMMMh             .hMMo                                       mMMMM.        oMMMMy           oMMMN-         `dMMMy`         +MMMN:         `hMMMh`       +MM-    yMMMM+     mMMMM-                                          
			                     mMMMM.                :MMMMh           `MMMMM`        :MMMMd           -sNMMN`                                       NMMMM.         dMMMM+           :dMMN+`      :mMMN+            -dMMNo`      :dMMN+         oMM-    -MMMN`     mMMMM-                                          
			                `oooyMMMMMdooo-         :oomMMMMMyo+     .oohMMMMMhoo.  +oomMMMMMyoooooooshmMMMMM+                                    -ooyMMMMMdoo/      .NMMMMhoo.        `/hNMms/:/odMMd+`               :yNMNs/:/odMMdo`       .osmMMmo+   dMMo   +oyMMMMMdoo.                                       
			                `/////////////.         -///////////     .///////////.  :////////////////////////                                     .///////////:       -///////.           `:+sssss+:.                    `:+osssso:.`         `////////   -//`   ///////////`                                      </pre>
         </div>
        

	
		<form action="${pageContext.servletContext.contextPath}/login" method="post">
			<p class = "text">Congratulations! You've managed not only to escape the rooms, but you've also found all of the treasure!</p>
			<div class="art">
        	<pre style = "font-size: 0.18vw;">
																																									                                                                                                                                                     -hmh+`                                                                                                                                                 
																																									                                                                                                                                                    -mosdmy                                                                                                                                                 
																																									                                                                                                                                                  -shd.`/dmd/                                                                                                                                               
																																									                                                                                                                                                 `dy.`` `+sdh`                                                                                                                                              
																																									                                                                                                                                               `:/ohyd++smyysyy+.                                                                                                                                           
																																									                                                                                                                                           `ohydoysmoh+/om:yh/yddhyo-                                                                                                                                       
																																									                                                                                                                                           oyo+: ``oo+` .sss: ``-yomd                                                                                                                                       
																																									                                                                                                                                           sh//:`.`syy`./hyh:`.-/+omy                                                                                                                                       
																																									                                                                                                                                           `+yyhhyhNoh/ssmodhosmyoo/`                                                                                                                                       
																																									                                                                                                                                             ```:++-`y+hhd.:syy/`                                                                                                                                           
																																									                                                                                                                                                 ``/ymddmmh/`                                                                                                                                               
																																									                                                                                                                                               .+yymhm+/ymmNy/.                                                                                                                                             
																																									                                                                                                                                             .oy+:ysh+  `hom+shy-                                                                                                                                           
																																									                                                                                                                                            /ho` +hoh:::/y/do`+hmo                                                                                                                                          
																																									                                                                                                                                           -d:   s+hoyooyo/hh`/hym/                                                                                                                                         
																																									                                                                                                                                           ss `.:h:dsh+/+yoyd:ssyyy`                                                                                                                                        
																																									                                                                                                                                          .d++ssyyymy:   yyshshhdhh`                                                                                                                                        
																																									                                                                                                                                          :hyyyyhy+:.    .+osyyyyhm/                                                                                                                                        
																																									                                                                                                                                          sddhoooo//+++o++/:/ssymmd:                                                                                                                                        
																																									                                                                                                                                          `ymsssyyyhyyyhyhhyyyyhNd.                                                                                                                                         
																																									                                                                                                                                           .dyhhhyo//+/+shydmdddmo.``                                                                                                                                       
																																									                                                                                                                                   ```   ./oydmh:.++oysyshhysyhsoyddy-`-/+++/.                                                                                                                              
																																									                                                                                                                           `...``.+yhys/oh:-..-omdhyssyyshhdN+`` :y/mdy+//ohNh+osss/.```.`                                                                                                                  
																																									                                                                                                            ````  .+sso+:/sysossyd/..:som:`+sy. dmNh+/:+shmyd`:s`:s.ds`   ohho-..:omhooosyy/.-+oo+-`                                                                                                        
																																									                                                                                                         `/oyyhyoyh+:/yohm+   so+m: `.dohs-.:N:.mNy``.-ho.hNN+.hyo+hNs`-++dy.    -dy.   -ysmho/::ohho``--``                                                                                                 
																																									                                                                                                 ./osss+:ho-`:yssNs`  om.dd  `/m/No.yhhodymmmo-yosmyo+++yhmdoms-+hmshmhsyhmy``/--ym-     oNs`    -ysmhyhhhho-                                                                                               
																																									                                                                                               `sy/..+syNy`   .Nosm- .sh:mm`.oyohhydhhddhsyyosd+/mh.   `+:dNo:hmh+/oyyyyyddmh++syhmo`:s+sdN:     `hmh:`  `osdy/                                                                                             
																																									                                                                                               +h`   `hyym- `./m/ymo:+oodhddhhhddsosyyyssyyhmm:-mN/    `h:+Nm/.hNNmhsso+ssysosssyhdmdhyyhmhh:`+ooymm-     +m:mm   `--..`                                                                                    
																																									                                                                            `        `/syyys+. os    `dy/Ns::oo+yNhddyysoooossossysossydmNdym/`ymmd-syshm+dmod..yNhsymNdhyssooossyyssooooooydhsssydm+ `:-:hh:my.oyooodmd`     -/os+:`          .+/:-.                                                       
																																									                                                        ./osys/`        .+ydddo-    +ho-  `/om+-mo. :oo+ddsmhyoo//o++osoo+/++/+sshmmhyhysyyms +Ns+ms+/-:/sdyymo `hd+hsssssshmNmhhys+/+/+oooo++ososohmh/ossoomNmm/    -ssdo. .odhhhdmmy-     .ossooshmh+`      `:-.                                          
																																									                                        ./oyddy/     `ohs+::/shd/     :yy+:---+dy. :d.    `ss/mh:+ydhhyyo+/o+osy+++/+ooshhhhdNNdhysosssyyo+h`.ddoy.   .o+ `sd+m: .my`-oyysoosysoysssyddmdhyso+::/++sssyydNdymNNo     `yy/Nh+h-    -s:hm.   :h-     +osNy`   .oyyhmh+:-`                                     
																																									                                      .yy+:-oyshy-  `yN/    `oh:do   /d-     :o-dd.yy`    `yh-mo:syo/:+/++//+oyhdddysoyyssysooosysosdy+. `d- oN+m-     .do .Nhoy` +m+   .+yysooossyoso/--::oydmmmhs/:/osssoshyds`    -ho+Nmd.     `sy-ms  -d:      :m/hNo  +h-   `yhhmd.                                    
																																									                                     -m:    `sm/od. .md.     .m+sm`  sy       m/oN/-d:`ooydy:hmyo++o+::+shhyso++oooosss++oooyyyshds/`    os``md-m:  `--+m+`/Nh/m. `yN-     `/ydhs+oso++sysoo+:/:+oshddho//osoosdh::oss++mNNd.     .hy:m+  -d-  `   :m+hm: -m`     /d::my      `.-:-.                        
																																									                        `-+oo+/.     sN`     -md-m: `sN/   .-od/dh   :d- :/--sd/dd+ohms///oys+/so/:ohdmhyoosooooo+ooosoossyhdyo:.`      .d. -Ns oh:`.omh+/omhood+  :Ny`       `-/ohdhys+oo+o+osssooo+sdmNmh+:+o++shyydmmdsdNy/sy+shd+dy`   od:`/ysyhosm/  :d      -ms:ms    -oyoosydh/`                     
																																									                      `oho-..:+yy.   /No`  -:hh+yh`` `smy+/ssosmh:::::smysymhssoyddhy:-ohms/os/:sdhsoo+/+o+osssoossyhddhyo/-`           +y  +N:  /mho///+hmhooody  `hm.            `-/oydddyso+ssoossoooooymmy+:yy:+mmssohsmy+:/+ymNhdyooooohddysshdmd/.``.ds`-ooods:mh.  `ys.    `-/dd.                    
																																									                     .yy`   `oy-od-   :dho/oyssdmsoyssosssssso+o++o+o++++hy.`  `+:+No`.ys-os:/hdhhssoo+++ooyhhddhyso/-``               `h/ `ym. :y:`  `/:`-hm:+hd`  /N/                 ``.:/oshddhhhhyyyyssyymmy/yy/sdydmh-      .ydysssoooo++oo++ooo+oooosdhyyysshds`   oh`     -m::No                    
																																									                     +m-      ms:N+`.:/ohysssso+++oso+++oooooossoo+ossoshs`     .m/yNoh//s/+dmmddddmddhyss+/:-.``                      -h` .my`:d-     .yo /N+ :d-  -Ns                        ```.-/+osyyhdddmmmmo/yy+hNm:      .+.mmdhhyyyysso++++++oosooo+o+ossyhdy+-.`so      -m+:Ns                    
																																									                     -d: `.`.omshNhyoosoooooo++ossyhddhdmddmmmmmmmmmmmmmN+     `+N++Ns-so:ddyoo+/:-..```                               oy  :No +m.     `hd.-Nd-`h/   dd`                                  ``````.:hd++h+sm/ ``   +y`dNNhdNNNdhhdddmmhddmdhyo//+/+ooo+:/oyyhm+`/ssydo:dm-                    
																																									                      :ys+yyydyysssssssoshdmmmmmdmNmyyhNNdmmmmmdddhhhhhyhd: /yyhh+/d::h:+ms.                                           y+  :N/ -N/ `+oosy--hmh/.d+`` dm-                                          `/ds:h++d//ysyyy/sNo://+oosyyhhhdmdhmNmddmmmmdhyo/:.  ``-+yyyyyoshmy.      ...`           
																																									          .:/oo/:-`    `/smdsoossooyhhdyyshhhhhhdmmhso+//:--...`````````+yyy+++o+yd:-y:od+`                                            d/  :N/  /hy/::///sddsdd.hy:s hm:                                            .hs-y+/mdsoooymdmh.       ````.--:+ssyhdmNNNNNNmhyy+:.   `:ohmms:`    -+syyyyy+.        
																																									        .yy/.`.//sd/   .oy+.`//yddysyhmydmmdyo+:.-.`                  `so.sd/ohsdm:-d:om/                                             `N:  +N:```:-hmmmmNyssysd`os.y om:                                             `oh-yooNyodhhdyyNd`                 ```.-/shmNNmhyyyhho:`  `.+hmy: `os:````.:sm+       
																																									       `hh.   `oh-om+-os/` ./ymhsyhydmmhs/-.`                         oy`sm.  -/yo.y:+N+                                              `m:  oN:o:-y+yyssydhoho+m.sy`/ om:                                              `yo-h/hN/s+s+y:yNo                        `.:+ymNdso:sdds-`  `:smysm.     +y.hd.      
																																									       .m+     -mo-mms/` .ohmhyssdNmho-`                             +moohyoo:`/h.oo-mh`                                              `m/  oN/+:yy:`   `.:hN/:y`ys ` ym:                                               .m:/h:mh+ysss+ohd/`                          `./ydh/`.:sdhs-   -ymm`.` `-hd.yd.      
																																									       `ys` ..-yh:yd+` .oddyosyyddo-`                              -oo-```.:/yyh/-y`ym:                                                d:/`+N/oyo`     `s--dho+ ys/+ ym.                                                sy`d/sNdy-`  -/+dd:                            `-odh/` -ohds.  `/dsoyyhho:+mo       
																																									        .ys:oossoyo.  /ddhysshmy/`                                `ho     `s+`dm.ss.Nh`                                                y/o/+N+oN-       sy.ddyo y//+`md`               ```..`                           -d:os:Nh`    `oh+md.                              .+dd/` `/hd+`  -ydyoooshd/`       
																																									         `-+ossdmo  .smNhsdmdh/`                                  .d-      /d.od`h::No                ``.....`            `-:/+ossy++::yo/s/NooNo` //--od++Nhys.h-s:-Ny           .:/oyhhddddyo:-.                      `ho:h`my      -m:dm.                                .+dy-  `+dh-  `oNmyo/:.         
																																									   ``.-..`    -y/  -dNmysmNd/`                                    `h/  ---+ho`hy d-oN:            `-/ohdhhdmdyho:.      .ohmmNNNdymsmhdds`s-No+shy+/osssoymd+h+/y-m:/Ndyso//:://oydmNNNNymhmNNmmmdyso++:.`               ys-d.mh. ...:yooNd.                                  .odo`  -yd:  `+md-    ``      
																																									 `/yooosyys/``h/  -dNmoshNy.                                       +m+.-///--sNo d-yN+//:-.````./shdsydhddmdmdNNmho-``.smNNNmhNdmomymhmsy`y-mh/y`hyddhhhmyhy+h+s+.y.sNNNNNNNmmddmmNNNNNmymsdddmmdyhddhhydyo-             sh-d.mmdo+syysymN-                                     :hs.  `yd:   omh`./+oosso-` 
																																									.yy-   .ooomyoo  `dNmohmmy`                                  ``.---syshysoshhhNo h.oNNNNNmdhhhdmdyhyysddsshomsmhmhdmyhmNNNNmmsmNNhmdmsdsm/s:hd:h y-odhNhd+oy+y/d:/::mNNNNNNNNNh+osNNNNmNhmdNhddhdhymdsdydyddo.           ys/h`mdshhdmmhNNN`                                      `oh.  `sm-   oNdho-` `:hms`
																																									od`     :N++Nh`  oNNyhmNh.                                -/shhyhhmNo .hdooho+ys s-/NNNNmmNNNNNNhydmhydhssdsmodhdhmyhNmmNymodomhmydomshdmy+++N:h.syso::/+sdys/`h-s oNNNNmmdNNNmdhmNNNhyNhmsmddmdhdhyy+mydshhdh+.`    `.-:h+sy.Nho+ossmshNm-.`                                     `+d-  `yd-  .dN+     //+m+
																																									oh`     -Ns:N+  :mmyosdm.                              `-ymNNddyhyhds  od:/yod+h.y/:NNNNhdNNNNNNmdNNdyyysshomodymymodmmyNsm+d/homsh/dohsmm:y:Nohdh:`   `-./mN:-y+o`hNNmmydyNNNhhmmNNNmmNmNhmymNmNNdhdsmod+hysysydysyyhdmmm-y/:Ns-//s/y-dNNmdho-`           `..-.-..```.`            +h.  .ms   +N/``  `sh:Ny
																																									-do` ./ohs/hh` .dNy/yoNs           ``......``      `.-odmmdommhyhyydd  -Nosooy/d/-s`mNdymhyhydhydhmdsshdssh+d+doh+ydddhhNyd/h+dsmyh+d:y+dy+s:mh+N:      +y`yN:s-o.oNNddmoddmNNdshymyNdmmdmNNNNdyhhshhomhmsdhsyoymyNddodNNy/h.omosysyh/ oNdmNNNmys+:---.--/shmmmmNmmdddmdyyo:.`      `yy   /m:  `mh+sosyhodm:
																																									 .oo++oosshms  /Nmoy/dd.      `-+syhdddmmhmdhysoooshdmmmdydsmmyyssydd:`+h+:-/oydo`y-oNNhdshddNohyohysshdood+mydhmhmsymmhdsdoh/h/dss/d+homoh++ym/m-     `+y-dmoy/+.mNmdhmodyNNNyyhdh+Nsmmymymhdhdyhosh+dshodmshhymomhhydNm:y+/md+-..-:oodNdmmNNNNNNNNmmmmmNmmdsmhmhmdmdmmNNNNmh/`     :m.  `hh   hNdyyssydh: 
																																									   `-://:-.h/  sms+h+Ny   `.:ohmNmmmdydmmmNhmmNNmmNdmdmdydh/dhosyyoyohys`  .oy/+d-:y.hNhysymNNmdy:h/hohhyydhNmdyd/+dhhhhhoy/y.y-hoo:h.ssdymoo:moss.:o+osy/hNdd:s-yNNNNddmdsNshhhdmmyN+sdyNhdydydohoys+dshoddshssdoNhhsdN++y.hh.    .o.oNNNmddsmmNNNmmhymyNmmdsmsmymhmhdddNNNNNNh-    `d+ /++m`  sNmoss++:`  
																																									          `d.  ydo+h+No`:sdmNNNNNyhysohsmydmNydsdyddmhmdsho-dh+soyoh/mh`     :mo/h.+o:mNNmNNNmmdmymsdsddssdmm+sshshhodhohoy/h-y:hos:h-ssdm+h/oym:mhysososmNmys+:oNmmmNydydsmhdyhhdmsNsys:msdyhsshd+oysh/mdhhsdoyh+mhdhmh-y.ym-      so:NNNmmNydsNmNdddomymmmmsmymdNhmydNmNmmNNNNm/`  `ys-+h/m.  +NN-        
																																									   `.-:-.`.d.  yd//yoNoyNNNNNNNmNyh+s/yod:hsNmy+hyNNhsdh+hs-dhsy+ssd+mh`     .my.Ns so/mmomyNmhhhod+ysmddsd+h.hsdhh+yyy:dshsdohohsy/myydyh+mh++dss//ddNmddNsh+osmNmmhdhdomhdyd+ydydomsyhom:syh+oyhsNmhyhdyhhsdooyod+ddy-s-/Nd. -.``-d/sNNNdhhsmydsmoddymhNdmhomsmsmsmsddommNNhmNNmy:``ohsyyyN/  :mN/://:.   
																																									 -ss+//+osym.  yd++osNNNNNNNmhhoy.s+sshoh-hsmoyoyodhhymd:hh+hh/yshoh+dds`  /os/-sNm/+yo+mmhdhm++s/mhhomod+y-homhm+h/+dh.ddyhs+hdyodsNmodsmommsssN+h-ssydmmNm+s+NmyNNmyydhh+d+yhdssy-do+hod+yososss+yoymymyhhshyyyyh/ys:s.+mydh:/syhyoyNdmNyhNydymhddmhdmoNdmmmmhmymsmsmyomdNmmNNNNNNdhhhhhsmN:  +Nmo/::+hy/ 
																																									/d/    -s/+N-  +m:o+oNNNNNhossyohodydsh+y.mNy+hyhsNNhdhy+d:/ddoyoyyh+dsmy+-..-+dmdoyy.+h+dmy+NydNhodhydod/y`h+hyh.h++mh+hysdodohyodsNy+d+msmdmdmmdys+/`:smNdy+mNNNmmhhyyhmsh/hooh+dod/+h+dohsdoyhsdyhdhdmshhhdyhoyNd++o.yd++ohdmhsymmdmddmsmhmmmdsdyNNdd/myhhymdmhmdNdmhdmsNhmNNNNNNNNNNNdoNm.  hm:    `.oNo
																																									m+      /N/ho  -mo::dNNNNd/syyysmoh+++hhs.hmh++y/yhmsodd-do-dh:sosyh/hodsmsoohNmyoh/+ysoy:hdsNohydohssyod+y-d+h/h:oysdhshhsh+hshhyhyhyyoodsysmNNh--oyo   `oNmmddmdddsydyymohohoss+d+Ndyyomohod/h+ssh+hyyyyhhmmydymsoy:/ds/o///ymyomNoyNNmmsmdymomdNymyyh+msdhsdhdhdymymNNNNNdhNNmNddNNNNNmmNy  .Nh`    +s-mm
																																									yo     `sm:hh`  yh.-:dNNNms/dNdsNoys+sd++:NNho+yoo+myd+h+h+shsossysh+hyhshd+``od+yssy/sy+yossNhdodomhyyodsh-mym/h-oyomshsh+y/d+yhdmsddsddmohsmmNy`-:.`    `dNmddmydhNmydsy.yoyysdsy/h+ddhmoyddsys/hooshohdmmydyds+s+:yhosoh+.o+/sdNNmdmyhmhdyhdhdhmmNmNdym+hyyhhhydhd+dymNymymNmsNNNNNNNNNNN+  +Nh.+::omosNy
																																									`o/ .+os+/sdd/  :N/o+NNNNdoyhhdddsd/dhhhdmmmsyoy:yoyhsoh-oh/mhsy/sddyddysshhy. -hyymyyy+d+syoohmNs...+dydydomod+dosy/yshohss/d:h+yh+ms/msmmo+oshho   //   .so++:/ymmNh+dohoh-+h/y:y.d:d+yh-d/m+hsoNoohy.  +Nhssoy//hh/shsosdo- /mNNydhmmNmydohy:dodohsNNNmsdyyhhdhhdmyd/dNNN+hshNmsmNNNNNNNs  :mNmyossoodNy`
																																									  :ooooosy/`-y` `sm:syNNNmmmyhhsmhmodyNNyyos/odN/y+m+myshsm+ymyhyhmmhhhyhshsmmo-:ho`-ohdmNdhsdshyd+::-+mN+modomodoyy+hoy/yyo:h.hoyy+mohhmdhs /so:    ++     /s/  sNNNdodoh+hoh+/d-dohhosym:y:y+h-hshod- -hmmhmyoymNho+/::. odyhddmdNmyd+mdohsNyhhhyod+ymmNoh+yhhhysdyod:mNdmyNsmNddNNmmNNNd. .dN+:shhhdmh.  
																																									    ````     /s  `dy/yNNNdhNNyhmhdNyshm+yoh/+oyyhdhssyhdod+sdd+symyydhmyddmmmyd+//+.    `-dNNys+omm+s-/mm:hNNmd/hoyy-h+y/ddo+h/dshh+dysohhhd` `/`    o/   `-`   `hmhmmhooh/doym+yssoh/s-m+oyoosd.ssoydd+---om:/hNm-  /++:`  `/mmmdymmyhhhm+dydomydodh+dyymodohyhsy+dsodsNmyNhmhmNNNNNddNNm. -dNs    `````   
																																									           ``.s+  -dh/mNNNNNdym+dNdhmNh-:y::oh/+shsNmNdhsos.sdhshmoy+NNdmhmhNd`oy.       `mo-`  /Nmsdymm+sm+mydydsys`yossyds+h`h/y+ymdNmo/os.  -o:   +-   :s/  .syhhyNNdys-m+doys+s-h:m-so/my+md:hsyNmymmNNNd`-+-`            .dNddNmhdhmhod/dym+d/dh+ds+dsNohodhdym/ommNmhhymmdNmmNNmmNh. :mNy-.`          
																																									        :oooosyms` .ydyNNNNNodhyNNNdsh-hoh/.sd:o+y+mhyh:/yo ohhhs+dohshymyhhmd`.`         . :-`:`yNNdy+hmNNodsh+yooy.hsosyd+oh+d:y+.mmmmd:.++    +o  o:  /+-    .: :mmmd+d/hod+/h:h:Nos/ss.d/yod-dhmddsdymNN:  :`      .+    -+syyoshmhhhyod/dod+h/mdhNhdyoNodydmmmm+ds+NNNNhmNydNmmNymy. /mmyooyhy/`       
																																									      -y/`  /o:-hh. `omdmNNNhm:dNNm/msoNdy+ooy//hs++y+yymNo/doymmooddhmhN/ //.                 .`hmmmNhdmodohho+do/h-yoosodooyyNhys/dyhdNm`      `s/ s: //     -do-dmyyohmodyod:h/ysshs os.h:N+d/hdhddsmNyyms`         +.     .  -o-mNNsyhdy/hodoh/m+hmoNoyhodymom+ms+soNmyNdmNmNNmyhmo``oNh-    `-dh.      
																																									     `m+    `-dy.hd/  -hNNNNNNhmNdhomydssh-ddh+sdyoh/om/modmydoydyhoyhhdhs` ` .`    ``     `    `-`.dNmym+doshyhdsyysshoyohososmhshhhyyhdmd+-` -: -h.d:`+  ./+sso/dNddhyyhysdNodmoohshh.hh+h/dsd/hhyyhhNNo`.`   .`    -y     ./`.y:sNNNmmhNdymmdyd+dsmoyhohosm/hydyy/mmmNNmNhmNNNmhmh: :dNm-.    o-sNo      
																																									     .m-     .ds`smos- `/hNNNNNNNydhNNNmhmoydyo-m/y/y/d:h`hyhdy/s/d/d/dsmmdo` .+:   .o   `+`       sNNydoyhh/mydmsdod+hydoh:s+shymm/`:+oyy+hmdo./o.m/m+  `+y:shdmmy+o+. +mddymshysoosyd/hh/d/ssyshmNhmmmhN:++    :-   o/   `/:` `+hNNmhmmNNymysyh+-m+hsysodo:h+d+mod+dmNsmhNmmNmymds..+mymd-yo::od:hN+      
																																									      oy` `/+s+`+m/ .oo. `:hNNNNNNmhNNNNNNmy/so+d+o-ysy/m:h+shs+ysohhdd/ds:-:.  :+` `y-  ++    `::.mNdsyhsdmyNosh:d.hohsddmohssyymmd-  `.//-dNNy`hsdsyys/:-.dNNds-/+/-`+mmsmdmydoyhoh+m+yhsd/yosmdd+syhddNs.oo+`  o` :h.  :+.    `-/hNmNmhNNNsd/hhshoh`yy.h+sd+dshmo-mydmNNNNNNmdy-`odd:`oNdo+ossohNy`      
																																									       -++//::+so-    .+o-``:sdNNNNhhyhNNNmmdNdmNdhydsm+m/m/h+oodys+ysmdmyo:`    :o  s+ `h.  `://odh+:::..dN+dy:s+h`ssshshyhdoshhdmNmh/    `-yy/+y/syys+/h/ `--`:+-` +dNmo:os++mmyh-dsm/dyomsmyhNNN/ :sooohdhs/`  y/ yy  ./   ``. -shddNmsmhhyd+hyyy+hoh/yhsod:mNoydys/:omNNNNNm:-odh/`  `/hmmddmmd+`       
																																									         `-:/::`        -+yy/..:sdmms+.+dNdNmNNmNhmyh-m/msm:h-o+h-s+mydhsNNmo`    ++ sh .d`  `sdmNy`  .:-ymdhhNdhyd/hyyyysyyhd/:///oys/.-  -oooh+:ds/mNm+-d+--:/o+:  /ss- .:--`hNdhyy/hsh/hNdhyshmNms/:.::.hNNm+  hy/No    `:+ys+/dmyhomshmdmmdsd:hhhs/m-/y-mssmNmmd.   .hNNmssmhmd+`      `.::::-`         
																																									                       `:os/ydy+-.:ysy.`hNdmshNdmhm:y-hoyyN/m/osh/hyd/sssyydmdys+``y:/d:/N:  `shh+`-` :ymNyoo/omhyyddyhohohhh: +//+-   .`   `.-h.yd.omNNd`sm+/::-``.---+:/-/ .s:hddNydohNhdmo./++++hNdho   -ydd//oyssyyy-  .sddddo+/hhyshmmymds-Nssdhyym/:m-hyhhdmNd- :ssy+yh`h/yhddho.                     
																																									            .-/+ooo:`.++::+.`:hmmhyy+//smNymd+msd+m:y/s/ysdsdyhydosyd. .oos/:yNNNs`sdso++shy+.```./:  ymh+` /oo-hmmhshdodomNy`   .----.--::/+osd`hy-mNNNm.oNsoo+++osyyoysh++-.h/`sNN/hshddds` ``.:``-/+:`/`+ooyy//ydhdy+ho`:dmds-   syo.ommmmmy.h+m+d+yd-+m+hhyddhmNmsoyhyo+dso/h:y:dmd+shyyo/.             
																																									          -oyo++oshmdd+ ./-   `hNddddmmddNNNNhh+d+m/h+y:h+sym+m/ddysdys-``.. `+yy-:h:+yddhs/sdy+/:.   `.``  ..ho:hNdoNh:hoNNh- ..-----.......--y/+m/oNNm+:dho+++/:.`````.y-`o+y-ommNydosdmh.    ..``    `.  `:d.om+-:mNh:m+.-::-  `/ddhhdyymshd:m+d/hs/y-mNdhdymmhmNNy.y/hmyym/d:y/+ydNyod+ddmdo`           
																																									         /y-` `+o+:+dm:   `   -mN+...yNhhdhmdmohmdmhdsd:d+h/m/yo/oydmhms    `--..:y-ym/:dNNs`ydo+++++s//-o    .:.omdhysyd+dydd.-s/`    :-    -osy/+hddy/-dy:`  `.-:  +so:/osyo:yNmhmyNshshyy``` .-:::://+///+ho/m+/sdNNm.dho+/-. -.yhhh-oyysydmsd+m/hyhy:ymhsmmNNmmNNmshs+yyhdhdomhms/y-yyhhhhNN+           
																																									         y+.+syhyoss+-   ./   .oo-  `hddmmmssNmmmmyNdhm:dyd+dm/.sys:/+-`   ``.:/+hs-Nh.+mNNm-:mh+/---:.` . `  ..-mydhmhhd:h/syh/::-:oy+.-  .:-.-.ohosooymy-o` .//.  `dNNmdy++sddhmydommmsd:m/-s/.   ` `....-/d+yd.mNNNNs/ms:.`` .+``-`` s/ds`dNmNsdodhmhhyyhms/mmymNNNysdy+/s-h++moy.+:ydhhyysmN/           
																																									         :yo/---/shs/`   ./    .+- `sdo+os+:`hNmydydNNNosymmsm. ``....::://++++:`os-Nd/NNNNm-+m:        .:-/++o/oNhdhmNdy:h:s+symddNmh+   +ddm/  +m+/+o:hs`` :mNNm+-o:+sdNNNNmshhhyhsNNNom:md++o:-+yy+`/    :sd+d+yNNmy:dyoooos+y+--+.../`/y.yNNdsmshdNmmhmmN//hyyyyhdddhyydo/s/+Ns.+ddho-``-hh+            
																																									          `       :yy.   `:     `:odh. `-``  smsddyNhmmoy/yhsy`    ...``````  ``.:d-yNy+mNNs-dh.       -dddyossydoysohhmo/d-yoysydom-   `ommyo. :d+  +y`.y/  `+mNNm:./o-.hNddmdsyhdsdNmdymomhNmddmmdh/  -oo-+-dyssyyyosds-    `.o--s+::so  o:/mNNNmdNNdhdyyydmmohoy:y-+yNmdoyd++sy.oNmo`     ``             
																																									                   `oh-   +`   :hmmN-`/`  `-odhosydNmNm+dhddNs:        `.`-o. :--:oyoshhdms/hh- /yhs.  `oshdsyhsh/hyssyd-.m-homyydsd` `.sNs-` `+o-  -dmo``oo.  -ohNd+.`` oNosmmmmmmoddyyydoy+yyymo-.`  :mmm+ .dhhhhyhmh:+:`     `yos`ooh+:-:/ymNydNNmds/+o-`./mmmmhyy:+.NNNmsyyom-sNm/                      
																																									                     /y:  ./ ` hNNds so  /dd+-::o--+ydmdmmmmNdms.     :ydd/``  ``` `ydyssyhmN.  sNNmh.  `++/mdhoy:hhdyyhd/mhyhdd/mddooydmm`  -/-   /dhdms``:s:   `ymhdyyshNmdmymmd+ohysssm+hyhhdd.   `:dmy/`.y+ .ydo/m+`:yho.   oNNmy/ysh/omdddmydNNNs +d.  .`hsmdmsms.+shmdhmsmsyNm+`                      
																																									                      .so- y+o:/o+- -y. `sy- `-o+/`.`oyhNdmmNsmNho:::smNds-`  :hds` ss--/s:-h+` `/yhmd/-../`mNmyh:so-.-:+hdysy+s:homydymdN+  `   .oNmohhNh+.`.`   oNNdmNNNmNdmsy+ds:`  .-sNNommNm:-/ohdo-  .s:  /my-`hh/omNNh- .shmdddmshhmmhmdmNmNNNh`h+`-/o/s:o.++y-++`+hssdmssNm/                        
																																									                        +yshdsdho-./y-   ```    -`-y.syhhNNddymNmsmdNNNh..o: `dhdy`:y.  smh-`ss:`/h+-hmhdyysdmmyhy:   -h.-mdmmos+h+yymsdomy```./ydmNh/ohdNNmyo/-.`mdmdmmmmhdhhhysN+   `h-`mm/hhhhddmmm-  `//` `omNm--/h+//hmmo.:sy/ymddmhNydshydddNNmN::- `/+yyho+-o/:ssddyhNNhhds-                         
																																									                         `:yNNNmhdmd-`.-://:`   :+s+.hmmhNNssdNmmohoNNNy `` `oNh/`-+`  /mmmd/.:ss/sy-hNddsyohhhhmN/ -/oh.:mmmdymhd/h+dym+ddyydmmhydmo..hyNNm+dNddhmmmdNyysdNNmddoN+.+/oh-/NydNNNsd+dym   /- `:ymdmNh//oh-``oNd:``o/+NdhmmNhdsmsmsdhmhNdo-.`.hsh:/oymddshNmddNNm+.                           
																																									                           smyhNmhmmdyo:.`    ./ss++hNhdsmydmhdNmdmymhNd--:ohmd.  ``  -mNshmmd+/+:./+mdsd+d+hhdsdddo://:odhdhNdmhdyN/y/m+dsdyNmmhNm/++.:sydNhhyyhymymdNydodmdm:yohmso+++ymNmNNmmddddhN.  `./ymmssdmNho/os` /mNmyo--hNmhdddomdmhNdmdmmNNNddhmNNNm/o-sm/hmss+hNNh`                            
																																									                           om/:mNNmomy`    `--dNdhmmNNddNmddhyo///sdNmmmmNNNmsm/  --`omdd+ohomNmms+/+mmmmmmdmdyshydNysddhd:hdmydymNhyhohsmsdsmodhy:++yh.`o+ymmdsymNdhdNNmyossoododdNddNNNhdydddhmdsyym+oshdNmdo++dmNNdhoo.-mNmymymmNhddh+:::+ddmyhsmmdmo/d+yyhdmysom+dm+hNNNNN/                             
																																									                           `hd/dNNNd+m:    .o.:+/-.:yNmmNmdNNo  -h/:mNhdymmmmmNm+ ./ddNh--..+ohmNhdhhdosysmmsyyhyyms:.-oshhmmmydomyy+h:h/d/hsmdy//o+hNhy: :oohmdmNNyyNNmN+hsmddh+hhy++hhdhdshyshddsyyydyhsmy-/ss//hyNNNNdsymhNdmdmhmymm.   -o:mhddhNNNy:ddh:y:syh-mmdNsoNNNNm+                              
																																									                            -hdsodNNmmh+.        .-``sNNhNNmhs`/sdo:mNhmsdydymNNh+hdmhm--ohs./soymmmNNmmmhh/hohsho-:oos--/+shddmsd+y/osdhd+ys/:+osyNmyydmo-`-:-+ydmoyNh+dhymymdho:/so``/+sdmsohddysyhodyds/:ooyNo +/hNNNNNNNNmhdydyh+ym.+++hy/mmNmdNmy+ydo.+-ydd/:yNNNmmNNms-                               
																																									                             `+hhdmNNy./+-   .os+:sy:`+ddNNmdyhosssmNNddodyh+h+hhyddNd:-ooNdy:.+ossymNydhyyhds+:-/++yNNmo/.:/+syyyosysso/-`` :oydNNNmyddmydh+-`  ``-/o+oooo++//+ooshNh:`-+osshhddyddhs+/.:o+smmdd-`o/ymNhdymhmhdsmsdodydsoyymmNNNNNNmhdyh+s+dNddh+hNNNNmh+-                                 
																																									                                ../dsss. --` /dNNhyoshhmNmmdNdmNNdyddhhhydsdsmohyNNdo.:o+mNdymh/.:+`.:::::-`  -+++ydmmNNhmmhs////:`````.-:/shddyNmhNmhNNNNmmNNmys+:-.````/oosssyhmNNNNNh/.`:/+/..``  `:/+osmNhddNm-`o-+mmdhmdyhdhd+domddhNNNNNNNhmNmdNhmNNNyys+somNNNNd.                                    
																																									                                   :mmNh+ooo: `:dmmhNyd/dddmNNNNy-o--/syhdydymdmhy/`://ymhhddohdmhs/-......-:/symmhyhhddyhddhhhyyssooosssssoooo+++///oo++oooooosyyyyyssyhhhdddddydddmmdmNmys+:--...--/oymNmmddNdNNms.:/.+hmhhNNshohms/+yodymNNNNddhNmNdmmNo+o+mhNhdNNN/                                     
																																									                                    odhsyNdhys/`oNNydyhsmhydmydy-s/hd/:+osy+//-.`  -symdhommNmmdmdddhsssoo+//:--.```  `                                                     ``````````..--:/+osyyhdddmsdhNydNNdhNNNNm/.   .:/++++:.-:+so./syNdmmohhNNdmmdmhmdNNNyhmNNy`                                     
																																									                                    `yhdhomNNhmddNmyNNmddyh+dh+-s/dNNNmyo/:-.-:/oyddmdhyo/oo+/.``                                  ``````````..````````````````````                                    `.-/oosshddmmdmmh/-``  `:+ooyyymNs o+smmmmdmNNdNNNNNNNNdydNNNd`                                      
																																									                                     `+mhy:smNNNNmmmNNNhdsdh/.:+smNNNNNmmmdysssyysooo+oo//oo++::-    ```...-:///+oossssyyhhddddhhdddmddddmddddddmmmmNNmmddhddddddmmmddddddhhyyysso+++/::---..```          `-:///++/..++osyhhhysyhhmNNNNNmo`/o+hmNNNhmyNNNNNmmydNNNNs`                                       
																																									                                       :yymo//symhmNNNmsy:-. /smNmhs+////+/++ossoo+/++:--/+++++ossyhdddmdhhhhyssooo+++/:::-....```````  ``  ``..-/+sy:hNs/.```` ```........-::/:/++osyyyhhhdddddddhyys+++//:..` -:` `ooso+/:.`.:/osydmmNNNh/.:`.+yhhddmddhsyymNNNh-                                         
																																									                                        `/hmmo` `.-:..```/dyyso:.` `///++oo+//+++osyhddddddhmh::dhsmNyoso+o:``                            :sssso+o+.  -+sysoooshh+`                    :///+oo+/++ooosoyymmysyydddhyssssso+s+/-///+/+h+ysymdms/.    ` :+ s+dymmo-                                           
																																									                                           `/osssoooossss+:.        ``-/oshddhhysyssyo++-+/+d/ `yh-dNh/+//////-                       ``.y+-+ossso+````:+o/+o++:+mdosyhs:`              .++++oo//+so++ooom: -yo.dmososyydhdhyysy+.-/ohodshsydsdshhssoossyddyo:`                                             
																																									                                               ``.-ohs-`        ./shdddyoooso++/++::/++:/+ohh/  -./yyysoso//////oo+:`               .ssoyh ``.+yhhhhhhdhhddy+-`/::s-.::sNh.          `://+ooooo+//+:/oydyy.  +syNd++ooo+soooososyhhhyydohsohsdyodsdymho:-.`                                                 
																																									                                                 `ss.      .:oydhso:-`` `://++/////--::+os/.``:sddy+oo+ooosyyhdy::sdm-            `:d+`/yh` `dh/-ossssmsssso+do    `:+d/sNs`        `:+o+oyo+smsohms+/:.``-/:-oydhoooooooooo+o+oooodydyddhhysssdyyhdhosy/                                                   
																																									                                                 -N.   `-ohdhs/.`    `:///:::/syydhoydy/``.+yhyoossshhyyysy+-//` .h+omy+          +ds. .oy  -N/ .hNNNNNNNNmmdmd    `+os..dmo`      ././shh:-ys:o:-..-:oyyddyhdyoshmddsooossooosssso+sdoysh+hsdmdyshyhsyody.                                                 
																																									                                                 `ys-`/hdy/.`        `::///:hd.:ssso:.`:shh+:-oyymmddyymmyo::.-``+o-ymy/           `+ho-:/`  +y+ohmNNNNNNNNNNd/  `` `.`/ho-         :/++yd- ./`   +dmNy++yyhyssddyss/+sssshhds/+hysoms++yoyysssyydd+/so/dNo                                                 
																																									                                                  `/shms::---.        ```:ohd: `oh`   .shmmhsoosdNNNNmho/++oshddo/odh.               -yddd+./-.:+syyysssssso/.`//+myoshm/            ````+ho/shs:.`-+sddyyymNmdhhNmdo `. .yhymsosysyyo+hyoosh+osssohh+yhNm/                                                 
																																									                                                     omyo+odmmyssso:..` `.+dds-:+-/+:.```./+shdmNNmho/:+oyhdhs+yyyy/`                 ``.`++/ooososo+: .///+++ssymo+sso-                 -+syy+oyyo:.`.:odNNmmdhhhos:-:/.`//:ymyossdsysh+dods+ymdmmhmmmho.                                                  
																																									                                                     .mmo+:/yss-:sssmh- /+/+-+yysdNhoyhso/-.``.-+y/.+oydddso+/::`                          `:osyyyys+-:ohhhhhhdys:                     `-`:::::+oooyyy/- .+o/ossyyyddhhdhooddyyo+oh/hdddhy+ydyyhddymNNy`                                                    
																																									                                                     -mhdNmy.   `/o+No .--.-::./soo+:/-///yyyy. .yo.dms/+/:/+//:```````...----:::-://///://///+++oooyddyssyysss+////////://::-:---..````.`.-::+ss++//ohd. /h/smmyssssso+osyssoooo+o+shd-.od..-/.ymdNNNy`                                                    
																																									                                                     +m-+NNNy`. ./omm-     ``-:`-.:/+:-/+/+oom+-:y+smm-:+o+++ooo+ooo+oo+++//:::::---........................---..-::--::::::////+oo++oooooo++/oss//:/syd/.+h+yNmssysyo++++o+oooo++sddym:`./`` .hdodNNNd`                                                    
																																									                                                     :NoyNNNm:o:hmyo:         ` .-`::-:///ooodhhyyyysoooo+:.`````                                                                       `````..----//+osysyyhmdssosyss+ossssso///oohhydmhhd:s`+N+yNNNNd`                                                    
																																									                                                      omsyNNm-o+dm`         `.-::/osssyyyoossyoss+++/--///::/:-           ````````.....-...----.--.-.......--.......````````                             :oossssosyyyysyosysossossyhohohyhmhhsdN/dNNNm/                                                     
																																									                                                      `/yhmNo./hmo   `.--/oosos++/+ososo+//++//+oo+//:.:+///+++::/+ooooosyyso+++++osoosooooossssyyssooooo+ooyssssssoosssoossooooooo+//+/:::-.....````   .//+++/+++oosssyyssyyyyydohsysdyyo+ddmmNdmNNd:                                                      
																																									                                                         .:hdhdh+-:+oso/:-.``./:/+++ooo+++++o+//oooosssysyyyyyyyyyyyysyhdNdhhhyhhhhdhhddddmmmmddddddhdhhddddmdddddhdhhhhhyyyyyhyyhyhyssssssoooososssso+++ooooo++++++o++++++++ooyhshsyshhohsyddmmhmNm-                                                       
																																									                                                           :No+oo+/-.`     .+//++osoosssosyyyyhhdhdddmmmmNNNmdddddddmohmmysss+------://oosyyhyss:-.-....-----------::--::://+++oo+oosyyyyhyhhhhhhhhdddhyhyhysossssysoo++o+/+++oyyohomhmhhyoooshNmho-                                                        
																																									                                                          .smo/.`     ``.:+ooydyhdhhddddhdmmNhyysosssshhhhdddyyssosssooosooo+.      .::/+//++////- ```                                  `` `..-ossshdhhhhhhhyysyyhNddhhdhhddhyssosooyyymNddhhodNy`                                                          
																																									                                                         /yo.     .-+sydmNNmdmNdysyddddyssssssyyyhysssssoosoo+///////://++++/.      .//++++++/++++++++.                                    -::/oooooooooosys`   .shyyyyymmmmdhmNNNmdysssyyhhmNdmd/                                                          
																																									                                                        :d-   `:+ydmmohdmmmdyyyyyhyhysssssssyysosysssoossoo//+//++oooyd++oo+/.      :+++++ooo++o+//+/`                               ...---/+/////++oo+ossyy/   `+sssyysyyhyyshhhyhNNmNmdhdyyhooNm:                                                         
																																									                                                        sy` -odNNNyyhhyyysyyyhhhyhyyyyssssssssssssssssssssssshysssoo+yho/::::-      /oso++//++/+/.```                               `//:+ososo++ooossoosyssyo`   /ysosoosyyssyyydyyyhhmNNNNmh+ooNN+                                                         
																																									                                                        /m+oNmdmmNNmdssssyyyhhyyysyssooooosyyoooosoosssssoossyyssoo+osssyssss+`    `/ososso+ooo+/-...`                                `.+oooosooosssssssssss`    :sssyssysyyydyhhdmNmmNNNNNNNmshms`                                                         
																																									                                                         /hmNmhssyhhdyyysysyyyyssyssssosyyosyysoooooo/+ssossysosssoooooo++o+/:`     :++++ooosssyyysso`                               -ooooooosoo++oo+/+++o+o:    -sosssyyyyyhmdhshhyymNNNNNNNNNd:`                                                          
																																									                                                          `:sdmhmmdyyyysyyyssssoossssyysyhyyysoooo+oo+o++ooo++++////////////+:      -/++oossssoo+++/:                               .+ooooooosssssssoooo+sss/    :sosssossoosyyhdmmmmmdNNNNmds/.                                                            
																																									                                                             `-ohdmNNNNNNdhyyysysysyysoo+++ossssyshyssooo++oo+oooo+ooosoo+o-:/     .ossssssssyossoo/`                            .-.-::///+//oososs+oooo+o+o:    -++ososdNmymmmmhyysyhdmdy+:`                                                               
																																									                                                                 `-/oyddmmNNddNNNmmdhyyyysossyyysosoo+oo++++:/++ooo++oooooo`-+     `+sssooosssossooso+                      ````./++//+////+++os+++oosossyyso...:oyyyhhhhhyyyyhmdmmdhs:``                                                                   
																																									                                                                      ``.-/oyhmmmNNNNNNmhyyyysyssoo+ososoosyo+++sssoosoosyy-./     `oooosso+ooo++o++++:                    -oo+oo++o+o++++//:://+oo++oooossyhhmhssmhyyyhddmmmdys/-.`                                                                        
																																									                                                                               `-//osyyhhdmmmNNmmmdhhhydysysyyyyyyyso+os+/+`:-     `+oooooooo/oooo+++++::`               `+/+ooosssssssysshyyyyyssssysoyyyhhmmNmmmmmdyoo/:-`                                                                                
																																									                                                                                          `..-:::/+oyyyhhdddmmmmNNNNNmmmmmdhddhhhhhhhhhhyyhhyhdhhhhhyyhyho+oossssssossosssssyhhyyhhhhshhhhhhdmmNNNmmdddyso+/:/::-.``                                                                                        
																																									                                                                                                           `````.---:///+ooosooosssysyyhhhhdmdddddmddmmmmmmmmmmmdmmmmddmmmdddmddhhssyso+++///:.--.``                                                                                                        

        	</pre>
        </div>
			<input class = "button" type="Submit" name="submit" value="Reset game and return to login">
		</form>
        
        
	</body>
</html>